version: "3.9"

services:
  shanaweb:
    container_name: shanaweb
    build:
      context: ./shanabunny
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  shanawebserver:
    container_name: shanawebserver
    build:
      context: ./shanaapiserver
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
    restart: unless-stopped
